[database]
# ROAST_DATABASE_POOL_SIZE
# Maximum number of connections to the database. Default is 10.
pool_size = 10

# ROAST_DATABASE_PATH
# SQLite database path.
path = "roast.sqlite3"

[export]
# ROAST_EXPORT_PATH
# Directory to export JSON files to
path = "public/api/jvm/"
