--
-- Create Table JAVA_META_DATA
--
DROP TABLE IF EXISTS JAVA_META_DATA;
CREATE TABLE JAVA_META_DATA (
    architecture TEXT NOT NULL,
    "checksum" TEXT,
    checksum_url TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    features TEXT,
    file_type TEXT,
    "filename" TEXT,
    image_type TEXT NOT NULL,
    java_version TEXT,
    jvm_impl TEXT,
    modified_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    os TEXT NOT NULL,
    release_type TEXT NOT NULL,
    "size" INTEGER,
    "url" TEXT NOT NULL,
    vendor TEXT NOT NULL,
    "version" TEXT NOT NULL,
    PRIMARY KEY ("url")
);

--
-- Create Indexes on JAVA_META_DATA
--
DROP INDEX IF EXISTS JAVA_META_DATA_IDX_ARCHITECTURE;
CREATE INDEX JAVA_META_DATA_IDX_ARCHITECTURE ON JAVA_META_DATA (architecture);

DROP INDEX IF EXISTS JAVA_META_DATA_IDX_OS;
CREATE INDEX JAVA_META_DATA_IDX_OS ON JAVA_META_DATA (os);

DROP INDEX IF EXISTS JAVA_META_DATA_IDX_VENDOR;
CREATE INDEX JAVA_META_DATA_IDX_VENDOR ON JAVA_META_DATA (vendor);

DROP INDEX IF EXISTS JAVA_META_DATA_IDX_VERSION;
CREATE INDEX JAVA_META_DATA_IDX_VERSION ON JAVA_META_DATA ("version");
